# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-14 08:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('Host', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('services', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('hostip', models.CharField(max_length=30)),
                ('service', models.CharField(max_length=30)),
                ('date', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('userhost', models.TextField()),
            ],
        ),
    ]
