# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-15 02:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showlog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usergroup',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('groupname', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='host',
            name='ID',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='ID',
            field=models.IntegerField(default=2, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='telephone',
            field=models.CharField(default=11, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='host',
            name='Host',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=30),
        ),
    ]
